---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/rh-perf-test-org/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-main-gooz
